/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: GUI_Font new song.c                                   *
* Font:        新宋体                                                *
* Height:      15                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 15                                            *
* Read pattern file: D:\Desktop\新建文本文档.txt                     *
* Read pattern file: D:\Desktop\新建文本文档.txt                     *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: D:\Desktop\新建文本文档.txt                     *
* Edit/Shift/Down    at character 0x6541 (25921)                     *
* Edit/Shift/Up      at character 0x6541 (25921)                     *
*                                                                    *
**********************************************************************
*/

#include "lgui_font.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontGUI_Fontnewsong;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Fontnewsong_4F60[ 30] = { /* code 4F60 */
  ____X__X,________,
  ____X__X,________,
  ____X_XX,XXXXXX__,
  ___X__X_,_____X__,
  ___X_X__,____X___,
  __XX____,_X______,
  _X_X____,_X______,
  ___X___X,_X_X____,
  ___X___X,_X__X___,
  ___X__X_,_X__X___,
  ___X__X_,_X___X__,
  ___X_X__,_X___X__,
  ___X____,_X______,
  ___X___X,XX______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Fontnewsong_5417[ 30] = { /* code 5417 */
  ________,________,
  ______XX,XXXX____,
  _XXXX___,___X____,
  _X__X__X,___X____,
  _X__X__X,___X____,
  _X__X__X,___X____,
  _X__X__X,XXXXXX__,
  _X__X___,_____X__,
  _X__X___,_____X__,
  _XXXX_XX,XXXX_X__,
  _X__X___,_____X__,
  ________,_____X__,
  ________,_____X__,
  ________,___XX___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Fontnewsong_597D[ 30] = { /* code 597D */
  ___X____,________,
  ___X___X,XXXXX___,
  ___X____,____X___,
  _XXXXX__,___X____,
  __X__X__,__X_____,
  __X__X__,__X_____,
  __X__X_X,XXXXXX__,
  _X___X__,__X_____,
  __X__X__,__X_____,
  ___XX___,__X_____,
  ____X___,__X_____,
  ___X_X__,__X_____,
  __X__X__,__X_____,
  _X______,XXX_____,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontGUI_Fontnewsong_CharInfo[3] = {
   {  16,  16,  2, acGUI_FontGUI_Fontnewsong_4F60 } /* code 4F60 */
  ,{  16,  16,  2, acGUI_FontGUI_Fontnewsong_5417 } /* code 5417 */
  ,{  16,  16,  2, acGUI_FontGUI_Fontnewsong_597D } /* code 597D */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontGUI_Fontnewsong_Prop3 = {
   0x597D /* first character */
  ,0x597D /* last character  */
  ,&GUI_FontGUI_Fontnewsong_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontGUI_Fontnewsong_Prop2 = {
   0x5417 /* first character */
  ,0x5417 /* last character  */
  ,&GUI_FontGUI_Fontnewsong_CharInfo[  1] /* address of first character */
  ,&GUI_FontGUI_Fontnewsong_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontGUI_Fontnewsong_Prop1 = {
   0x4F60 /* first character */
  ,0x4F60 /* last character  */
  ,&GUI_FontGUI_Fontnewsong_CharInfo[  0] /* address of first character */
  ,&GUI_FontGUI_Fontnewsong_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontGUI_Fontnewsong = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,15 /* height of font  */
  ,15 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontGUI_Fontnewsong_Prop1}
  ,13 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,10 /* Height of capital characters */
};

