/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: GUI_Font8_1.c                                         *
* Font:        ÐÂËÎÌå                                                *
* Height:      15                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 15                                            *
*                                                                    *
**********************************************************************
*/

#include "lgui_font.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontGUI_Font8_1;

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0020[ 15] = { /* code 0020 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0021[ 15] = { /* code 0021 */
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0022[ 15] = { /* code 0022 */
  ________,
  ___X_X__,
  __X_X___,
  __X_X___,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0023[ 15] = { /* code 0023 */
  ________,
  ________,
  ________,
  ___X_X__,
  ___X_X__,
  _XXXXXX_,
  ___X_X__,
  ___X_X__,
  __X_X___,
  _XXXXXX_,
  __X_X___,
  __X_X___,
  __X_X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0024[ 15] = { /* code 0024 */
  ________,
  ________,
  ___X____,
  __XXX___,
  _X_X_X__,
  _X_X_X__,
  _X_X____,
  __XX____,
  ___XX___,
  ___X_X__,
  _X_X_X__,
  _X_X_X__,
  __XXX___,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0025[ 15] = { /* code 0025 */
  ________,
  ________,
  ________,
  _X___X__,
  X_X__X__,
  X_X_X___,
  X_X_X___,
  _X_X____,
  ___X_X__,
  __X_X_X_,
  __X_X_X_,
  _X__X_X_,
  _X___X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0026[ 15] = { /* code 0026 */
  ________,
  ________,
  ________,
  __X_____,
  _X_X____,
  _X_X____,
  _X_X____,
  _XXXXX__,
  X_X_X___,
  X_X_X___,
  X__XX___,
  X___X___,
  _XXX_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0027[ 15] = { /* code 0027 */
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0028[ 15] = { /* code 0028 */
  ________,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  _____X__,
  ______X_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0029[ 15] = { /* code 0029 */
  ________,
  _X______,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_002A[ 15] = { /* code 002A */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  XX_X_XX_,
  __XXX___,
  __XXX___,
  XX_X_XX_,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_002B[ 15] = { /* code 002B */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_002C[ 15] = { /* code 002C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_002D[ 15] = { /* code 002D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_002E[ 15] = { /* code 002E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_002F[ 15] = { /* code 002F */
  ________,
  ______X_,
  _____X__,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0030[ 15] = { /* code 0030 */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0031[ 15] = { /* code 0031 */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0032[ 15] = { /* code 0032 */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X____X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0033[ 15] = { /* code 0033 */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _____X__,
  ___XX___,
  _____X__,
  ______X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0034[ 15] = { /* code 0034 */
  ________,
  ________,
  ________,
  ____X___,
  ____X___,
  ___XX___,
  __X_X___,
  _X__X___,
  _X__X___,
  _XXXXXX_,
  ____X___,
  ____X___,
  ___XXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0035[ 15] = { /* code 0035 */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  ______X_,
  ______X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0036[ 15] = { /* code 0036 */
  ________,
  ________,
  ________,
  ___XXX__,
  __X__X__,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0037[ 15] = { /* code 0037 */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___X__,
  _X___X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0038[ 15] = { /* code 0038 */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0039[ 15] = { /* code 0039 */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_X_,
  ______X_,
  ______X_,
  __X__X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_003A[ 15] = { /* code 003A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_003B[ 15] = { /* code 003B */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_003C[ 15] = { /* code 003C */
  ________,
  ________,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_003D[ 15] = { /* code 003D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_003E[ 15] = { /* code 003E */
  ________,
  ________,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_003F[ 15] = { /* code 003F */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0040[ 15] = { /* code 0040 */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X__XX_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_XX_X__,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0041[ 15] = { /* code 0041 */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  _XXXXX__,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0042[ 15] = { /* code 0042 */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  XXXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0043[ 15] = { /* code 0043 */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  X_____X_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0044[ 15] = { /* code 0044 */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0045[ 15] = { /* code 0045 */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X____X_,
  XXXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0046[ 15] = { /* code 0046 */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0047[ 15] = { /* code 0047 */
  ________,
  ________,
  ________,
  __XXXX__,
  _X___X__,
  X____X__,
  X_______,
  X_______,
  X_______,
  X___XXX_,
  X____X__,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0048[ 15] = { /* code 0048 */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXXX__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0049[ 15] = { /* code 0049 */
  ________,
  ________,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_004A[ 15] = { /* code 004A */
  ________,
  ________,
  ________,
  __XXXXX_,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_004B[ 15] = { /* code 004B */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X__X___,
  _X__X___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_004C[ 15] = { /* code 004C */
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_004D[ 15] = { /* code 004D */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  XX_X_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_004E[ 15] = { /* code 004E */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _XX__X__,
  _XX__X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X__XX__,
  _X__XX__,
  _X__XX__,
  XXX__X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_004F[ 15] = { /* code 004F */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0050[ 15] = { /* code 0050 */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0051[ 15] = { /* code 0051 */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_XX__X_,
  _X__XX__,
  __XXX___,
  _____XX_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0052[ 15] = { /* code 0052 */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X_X____,
  _X__X___,
  _X__X___,
  _X___X__,
  XXX__XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0053[ 15] = { /* code 0053 */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  _X______,
  __XX____,
  ____XX__,
  ______X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0054[ 15] = { /* code 0054 */
  ________,
  ________,
  ________,
  XXXXXXX_,
  X__X__X_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0055[ 15] = { /* code 0055 */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0056[ 15] = { /* code 0056 */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0057[ 15] = { /* code 0057 */
  ________,
  ________,
  ________,
  XX_X_XX_,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _XX_XX__,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0058[ 15] = { /* code 0058 */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  __X_X___,
  __X_X___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0059[ 15] = { /* code 0059 */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_005A[ 15] = { /* code 005A */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X___X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X___X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_005B[ 15] = { /* code 005B */
  ________,
  ___XXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___XXXX_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_005C[ 15] = { /* code 005C */
  ________,
  ________,
  _X______,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  _____X__,
  _____X__,
  _____X__,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_005D[ 15] = { /* code 005D */
  ________,
  _XXXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  _XXXX___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_005E[ 15] = { /* code 005E */
  ________,
  ___XX___,
  __X__X__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_005F[ 15] = { /* code 005F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0060[ 15] = { /* code 0060 */
  ________,
  _XX_____,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0061[ 15] = { /* code 0061 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  ___XXX__,
  __X__X__,
  _X___X__,
  _X___X__,
  __XXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0062[ 15] = { /* code 0062 */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0063[ 15] = { /* code 0063 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XXX__,
  __X___X_,
  _X______,
  _X______,
  _X______,
  __X___X_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0064[ 15] = { /* code 0064 */
  ________,
  ________,
  ________,
  _____XX_,
  ______X_,
  ______X_,
  __XXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0065[ 15] = { /* code 0065 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _XXXXXX_,
  _X______,
  _X______,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0066[ 15] = { /* code 0066 */
  ________,
  ________,
  ________,
  ____XXX_,
  ___X__X_,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0067[ 15] = { /* code 0067 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X___X__,
  _X___X__,
  __XXX___,
  _X______,
  __XXXX__,
  _X____X_,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0068[ 15] = { /* code 0068 */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0069[ 15] = { /* code 0069 */
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_006A[ 15] = { /* code 006A */
  ________,
  ________,
  ________,
  ____XX__,
  ____XX__,
  ________,
  ___XXX__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _X___X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_006B[ 15] = { /* code 006B */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X__XXX_,
  _X__X___,
  _X_X____,
  _XX_X___,
  _X__X___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_006C[ 15] = { /* code 006C */
  ________,
  ________,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_006D[ 15] = { /* code 006D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  XX_X_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_006E[ 15] = { /* code 006E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_006F[ 15] = { /* code 006F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0070[ 15] = { /* code 0070 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0071[ 15] = { /* code 0071 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_X_,
  ______X_,
  _____XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0072[ 15] = { /* code 0072 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  __XX__X_,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0073[ 15] = { /* code 0073 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___X__,
  _X______,
  __XXX___,
  _____X__,
  _X___X__,
  _XXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0074[ 15] = { /* code 0074 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0075[ 15] = { /* code 0075 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0076[ 15] = { /* code 0076 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X_X___,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0077[ 15] = { /* code 0077 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_X_XX_,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  __X_X___,
  __X_X___,
  __X_X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0078[ 15] = { /* code 0078 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_XXX_,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  _XXX_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_0079[ 15] = { /* code 0079 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_007A[ 15] = { /* code 007A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___X__,
  ____X___,
  ___X____,
  ___X____,
  __X___X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_007B[ 15] = { /* code 007B */
  ________,
  ____XX__,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ___X____,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____XX__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_007C[ 15] = { /* code 007C */
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_007D[ 15] = { /* code 007D */
  ________,
  __XX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XX____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_007E[ 15] = { /* code 007E */
  __XX___X,
  _X__X__X,
  _X___XX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_007F[ 15] = { /* code 007F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00A0[ 30] = { /* code 00A0 */
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00A1[ 15] = { /* code 00A1 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00A2[ 15] = { /* code 00A2 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00A3[ 15] = { /* code 00A3 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00A4[ 30] = { /* code 00A4 */
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00A5[ 15] = { /* code 00A5 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00A6[ 15] = { /* code 00A6 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00A7[ 30] = { /* code 00A7 */
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00A8[ 30] = { /* code 00A8 */
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00A9[ 15] = { /* code 00A9 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00AA[ 15] = { /* code 00AA */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00AB[ 15] = { /* code 00AB */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00AC[ 15] = { /* code 00AC */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00AD[ 15] = { /* code 00AD */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00AE[ 15] = { /* code 00AE */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00AF[ 15] = { /* code 00AF */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00B0[ 30] = { /* code 00B0 */
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00B1[ 30] = { /* code 00B1 */
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00B2[ 15] = { /* code 00B2 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00B3[ 15] = { /* code 00B3 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00B4[ 15] = { /* code 00B4 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00B5[ 15] = { /* code 00B5 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00B6[ 15] = { /* code 00B6 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00B7[ 30] = { /* code 00B7 */
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00B8[ 15] = { /* code 00B8 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00B9[ 15] = { /* code 00B9 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00BA[ 15] = { /* code 00BA */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00BB[ 15] = { /* code 00BB */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00BC[ 15] = { /* code 00BC */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00BD[ 15] = { /* code 00BD */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00BE[ 15] = { /* code 00BE */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00BF[ 15] = { /* code 00BF */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00C0[ 15] = { /* code 00C0 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00C1[ 15] = { /* code 00C1 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00C2[ 15] = { /* code 00C2 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00C3[ 15] = { /* code 00C3 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00C4[ 15] = { /* code 00C4 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00C5[ 15] = { /* code 00C5 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00C6[ 15] = { /* code 00C6 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00C7[ 15] = { /* code 00C7 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00C8[ 15] = { /* code 00C8 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00C9[ 15] = { /* code 00C9 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00CA[ 15] = { /* code 00CA */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00CB[ 15] = { /* code 00CB */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00CC[ 15] = { /* code 00CC */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00CD[ 15] = { /* code 00CD */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00CE[ 15] = { /* code 00CE */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00CF[ 15] = { /* code 00CF */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00D0[ 15] = { /* code 00D0 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00D1[ 15] = { /* code 00D1 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00D2[ 15] = { /* code 00D2 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00D3[ 15] = { /* code 00D3 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00D4[ 15] = { /* code 00D4 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00D5[ 15] = { /* code 00D5 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00D6[ 15] = { /* code 00D6 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00D7[ 30] = { /* code 00D7 */
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00D8[ 15] = { /* code 00D8 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00D9[ 15] = { /* code 00D9 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00DA[ 15] = { /* code 00DA */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00DB[ 15] = { /* code 00DB */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00DC[ 15] = { /* code 00DC */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00DD[ 15] = { /* code 00DD */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00DE[ 15] = { /* code 00DE */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00DF[ 15] = { /* code 00DF */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00E0[ 15] = { /* code 00E0 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00E1[ 15] = { /* code 00E1 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00E2[ 15] = { /* code 00E2 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00E3[ 15] = { /* code 00E3 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00E4[ 15] = { /* code 00E4 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00E5[ 15] = { /* code 00E5 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00E6[ 15] = { /* code 00E6 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00E7[ 15] = { /* code 00E7 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00E8[ 15] = { /* code 00E8 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00E9[ 15] = { /* code 00E9 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00EA[ 15] = { /* code 00EA */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00EB[ 15] = { /* code 00EB */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00EC[ 15] = { /* code 00EC */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00ED[ 15] = { /* code 00ED */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00EE[ 15] = { /* code 00EE */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00EF[ 15] = { /* code 00EF */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00F0[ 15] = { /* code 00F0 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00F1[ 15] = { /* code 00F1 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00F2[ 15] = { /* code 00F2 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00F3[ 15] = { /* code 00F3 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00F4[ 15] = { /* code 00F4 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00F5[ 15] = { /* code 00F5 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00F6[ 15] = { /* code 00F6 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00F7[ 30] = { /* code 00F7 */
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00F8[ 15] = { /* code 00F8 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00F9[ 15] = { /* code 00F9 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00FA[ 15] = { /* code 00FA */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00FB[ 15] = { /* code 00FB */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00FC[ 15] = { /* code 00FC */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00FD[ 15] = { /* code 00FD */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00FE[ 15] = { /* code 00FE */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontGUI_Font8_1_00FF[ 15] = { /* code 00FF */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontGUI_Font8_1_CharInfo[192] = {
   {   8,   8,  1, acGUI_FontGUI_Font8_1_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0021 } /* code 0021 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0022 } /* code 0022 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0023 } /* code 0023 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0024 } /* code 0024 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0025 } /* code 0025 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0026 } /* code 0026 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0027 } /* code 0027 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0028 } /* code 0028 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0029 } /* code 0029 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_002A } /* code 002A */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_002B } /* code 002B */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_002C } /* code 002C */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_002D } /* code 002D */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_003A } /* code 003A */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_003B } /* code 003B */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_003C } /* code 003C */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_003D } /* code 003D */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_003E } /* code 003E */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_003F } /* code 003F */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0040 } /* code 0040 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0044 } /* code 0044 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0045 } /* code 0045 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0047 } /* code 0047 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0048 } /* code 0048 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_004A } /* code 004A */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_004B } /* code 004B */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_004C } /* code 004C */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_004D } /* code 004D */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_004E } /* code 004E */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0051 } /* code 0051 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0052 } /* code 0052 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0055 } /* code 0055 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0056 } /* code 0056 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0057 } /* code 0057 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0059 } /* code 0059 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_005A } /* code 005A */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_005B } /* code 005B */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_005C } /* code 005C */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_005D } /* code 005D */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_005E } /* code 005E */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_005F } /* code 005F */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0060 } /* code 0060 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0063 } /* code 0063 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0064 } /* code 0064 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0065 } /* code 0065 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0066 } /* code 0066 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0068 } /* code 0068 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0069 } /* code 0069 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_006A } /* code 006A */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_006B } /* code 006B */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_006C } /* code 006C */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_006F } /* code 006F */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0071 } /* code 0071 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0072 } /* code 0072 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0073 } /* code 0073 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0075 } /* code 0075 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0076 } /* code 0076 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0077 } /* code 0077 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0078 } /* code 0078 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_0079 } /* code 0079 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_007A } /* code 007A */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_007B } /* code 007B */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_007C } /* code 007C */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_007D } /* code 007D */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_007E } /* code 007E */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_007F } /* code 007F */
  ,{  15,  15,  2, acGUI_FontGUI_Font8_1_00A0 } /* code 00A0 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00A1 } /* code 00A1 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00A2 } /* code 00A2 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00A3 } /* code 00A3 */
  ,{  16,  16,  2, acGUI_FontGUI_Font8_1_00A4 } /* code 00A4 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00A5 } /* code 00A5 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00A6 } /* code 00A6 */
  ,{  16,  16,  2, acGUI_FontGUI_Font8_1_00A7 } /* code 00A7 */
  ,{  16,  16,  2, acGUI_FontGUI_Font8_1_00A8 } /* code 00A8 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00A9 } /* code 00A9 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00AA } /* code 00AA */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00AB } /* code 00AB */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00AC } /* code 00AC */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00AD } /* code 00AD */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00AE } /* code 00AE */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00AF } /* code 00AF */
  ,{  16,  16,  2, acGUI_FontGUI_Font8_1_00B0 } /* code 00B0 */
  ,{  16,  16,  2, acGUI_FontGUI_Font8_1_00B1 } /* code 00B1 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00B2 } /* code 00B2 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00B3 } /* code 00B3 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00B4 } /* code 00B4 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00B5 } /* code 00B5 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00B6 } /* code 00B6 */
  ,{  16,  16,  2, acGUI_FontGUI_Font8_1_00B7 } /* code 00B7 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00B8 } /* code 00B8 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00B9 } /* code 00B9 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00BA } /* code 00BA */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00BB } /* code 00BB */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00BC } /* code 00BC */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00BD } /* code 00BD */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00BE } /* code 00BE */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00BF } /* code 00BF */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00C0 } /* code 00C0 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00C1 } /* code 00C1 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00C2 } /* code 00C2 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00C3 } /* code 00C3 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00C4 } /* code 00C4 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00C5 } /* code 00C5 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00C6 } /* code 00C6 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00C7 } /* code 00C7 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00C8 } /* code 00C8 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00C9 } /* code 00C9 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00CA } /* code 00CA */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00CB } /* code 00CB */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00CC } /* code 00CC */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00CD } /* code 00CD */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00CE } /* code 00CE */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00CF } /* code 00CF */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00D0 } /* code 00D0 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00D1 } /* code 00D1 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00D2 } /* code 00D2 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00D3 } /* code 00D3 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00D4 } /* code 00D4 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00D5 } /* code 00D5 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00D6 } /* code 00D6 */
  ,{  16,  16,  2, acGUI_FontGUI_Font8_1_00D7 } /* code 00D7 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00D8 } /* code 00D8 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00D9 } /* code 00D9 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00DA } /* code 00DA */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00DB } /* code 00DB */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00DC } /* code 00DC */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00DD } /* code 00DD */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00DE } /* code 00DE */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00DF } /* code 00DF */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00E0 } /* code 00E0 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00E1 } /* code 00E1 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00E2 } /* code 00E2 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00E3 } /* code 00E3 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00E4 } /* code 00E4 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00E5 } /* code 00E5 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00E6 } /* code 00E6 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00E7 } /* code 00E7 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00E8 } /* code 00E8 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00E9 } /* code 00E9 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00EA } /* code 00EA */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00EB } /* code 00EB */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00EC } /* code 00EC */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00ED } /* code 00ED */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00EE } /* code 00EE */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00EF } /* code 00EF */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00F0 } /* code 00F0 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00F1 } /* code 00F1 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00F2 } /* code 00F2 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00F3 } /* code 00F3 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00F4 } /* code 00F4 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00F5 } /* code 00F5 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00F6 } /* code 00F6 */
  ,{  16,  16,  2, acGUI_FontGUI_Font8_1_00F7 } /* code 00F7 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00F8 } /* code 00F8 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00F9 } /* code 00F9 */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00FA } /* code 00FA */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00FB } /* code 00FB */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00FC } /* code 00FC */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00FD } /* code 00FD */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00FE } /* code 00FE */
  ,{   8,   8,  1, acGUI_FontGUI_Font8_1_00FF } /* code 00FF */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontGUI_Font8_1_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontGUI_Font8_1_CharInfo[ 96] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontGUI_Font8_1_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontGUI_Font8_1_CharInfo[  0] /* address of first character */
  ,&GUI_FontGUI_Font8_1_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontGUI_Font8_1 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,15 /* height of font  */
  ,15 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontGUI_Font8_1_Prop1}
  ,13 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,10 /* Height of capital characters */
};

